### ISSUE TITLE
Cashapp clone

### ISSUE THREAD

**Issue by ady4657** [culturally/CashApp#23]

**Comment by scammingscammers101** [comment]
Honestly as someone who doesn't have any experience in coding or any of this stuff, i was hoping i could just follow the steps and be done with it, but after literal hours of working on things to archive it, a plethora of issues that i cant even begin to try and understand showed up and honestly i am really annoyed due to the fact that i have literally been trying since 11:30 and it is now 3:17 in the morning and despite it being the one thing i didn't want to do before going to bed, i have to just give up.

**Comment by ady4657** [comment]
What this is about?

**Comment by scammingscammers101** [comment]
Honestly mate I don’t know sorry for being so rude but I have been working with chat gpt for hours to try and get this working and there are three lines of code that say ‘ambiguous use of transition’ and I have no idea what that meansOn 27 Dec 2024, at 3:56 am, ady4657 ***@***.***> wrote:﻿
What this is about?



On Fri, Dec 27, 2024, 5:18 AM scammingscammers101 ***@***.***>

wrote:

**Comment by ady4657** [comment]
Umm.. ok, don't worry, stay chill! God bless you!
